version: "3.3"

services:

  zhibo8:
    image: "xdream76/zhibo8-api"
    container_name: "zhibo8api"
    restart: unless-stopped
    ports:
      - "8022:8001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config.toml:/app/config.toml:ro