[database]
address = "192.168.50.17"
user = "xdream"
password = "sima5654"
name = "zhibo8_v3"

[app]
version = "2021.0408.0013"
DEFAULT_TEAMS_STRING = '勇士,北京,北控,掘金,热刺,埃弗顿,F1,皇家马德里'
GRAB_TIMER_BASE = 1800
TIMER_RANDOM_SEED = 1800
